/** Shared mock inbox for mobile Notifications — types match live system. */

import {
  getNotificationCta,
  getNotificationTypeTone,
} from '../utils/notificationTypes';

export function getNotificationIcon(type = '') {
  return getNotificationTypeTone(type);
}

export function getNotificationAction(item) {
  return getNotificationCta(item, 'app');
}

export const MOCK_NOTIFICATIONS = [
  {
    id: 'n5',
    type: 'weekend_offer',
    title: 'Weekend outdoor sale',
    desc: 'Up to 15% off Sunhaven outdoor lounge — this weekend only.',
    body: 'Refresh your patio with the Sunhaven Outdoor Lounge Set. Limited stock for this weekend. Use code WEEKEND15 at checkout.',
    time: '2 hours ago',
    unread: true,
    productImage: 'product-images/sunhaven-outdoor-lounge-set-main.jpeg.jpeg',
    productName: 'Sunhaven Outdoor Lounge Set',
    couponCode: 'WEEKEND15',
  },
  {
    id: 'n1',
    type: 'order_shipped',
    title: 'Out for delivery',
    desc: 'Order #ORD-2024-0002 is on the way. Estimated delivery today.',
    body: 'Your furniture left our warehouse and is with driver Mohamed Ali. Keep your phone nearby — he may call when he arrives.',
    time: '2 min ago',
    unread: true,
    orderId: 'ORD-2024-0002',
  },
  {
    id: 'n2',
    type: 'payment_success',
    title: 'Payment confirmed',
    desc: 'We received your EVC Plus payment of $419.00.',
    body: 'Payment for order #ORD-2024-0002 was confirmed successfully via Waafi / EVC Plus. Your order is now being prepared.',
    time: '1 hour ago',
    unread: true,
    orderId: 'ORD-2024-0002',
  },
  {
    id: 'n3',
    type: 'order_placed',
    title: 'Order placed',
    desc: 'Your order #ORD-2024-0003 has been placed successfully.',
    body: 'Thanks for shopping with MMF. We will notify you when payment clears and when packing starts.',
    time: 'Yesterday',
    unread: true,
    orderId: 'ORD-2024-0003',
  },
  {
    id: 'n4',
    type: 'driver_assigned',
    title: 'Driver assigned',
    desc: 'Mohamed Ali will deliver your furniture.',
    body: 'A delivery driver has been assigned to order #ORD-2024-0002. You can track progress from My Orders.',
    time: 'Yesterday',
    unread: true,
    orderId: 'ORD-2024-0002',
  },
  {
    id: 'n5b',
    type: 'coupon_offer',
    title: 'Special offer — HOME10',
    desc: 'Save 10% on living room sets this week.',
    body: 'Use code HOME10 at checkout on selected living room furniture. Offer ends Sunday at midnight Mogadishu time.',
    time: '2 days ago',
    unread: false,
    couponCode: 'HOME10',
    productImage: 'product-images/ivory-luxe-living-room-set-main.jpeg.jpeg',
    productName: 'Ivory Luxe Living Room Set',
  },
  {
    id: 'n6',
    type: 'wishlist_stock',
    title: 'Back in stock',
    desc: 'Olive Curve Lounge Chair is available again.',
    body: 'An item from your wishlist is back in stock. Add it to cart before it sells out again.',
    time: '3 days ago',
    unread: false,
    productImage: 'product-images/olive-curve-lounge-chair-main.jpeg.png',
    productName: 'Olive Curve Lounge Chair',
  },
  {
    id: 'n7',
    type: 'review_reminder',
    title: 'Rate your order',
    desc: 'How was your Ivory Luxe Living Room Set?',
    body: 'Your order was delivered. Rate the delivery and products to help other customers — it only takes a minute.',
    time: '4 days ago',
    unread: false,
    orderId: 'ORD-2024-0001',
  },
  {
    id: 'n8',
    type: 'support_replied',
    title: 'Support replied',
    desc: 'Customer Service answered your message.',
    body: 'Our team replied to your support chat about delivery timing. Open the conversation to continue.',
    time: '5 days ago',
    unread: false,
  },
  {
    id: 'n9',
    type: 'order_processing',
    title: 'Order is processing',
    desc: 'We are preparing #ORD-2024-0003 for shipment.',
    body: 'Your payment is confirmed and our warehouse team is packing your items carefully.',
    time: '5 days ago',
    unread: false,
    orderId: 'ORD-2024-0003',
  },
  {
    id: 'n10',
    type: 'payment_failed',
    title: 'Payment failed',
    desc: 'EVC Plus payment for #ORD-2024-0004 did not complete.',
    body: 'No charge was finalized. You can retry payment from the order or place a new order when ready.',
    time: '6 days ago',
    unread: false,
    orderId: 'ORD-2024-0004',
  },
  {
    id: 'n11',
    type: 'order_delivered',
    title: 'Delivered',
    desc: 'Order #ORD-2024-0001 was delivered successfully.',
    body: 'Thank you for choosing Mogadishu Modern Furniture. Please check your items and leave a review when you can.',
    time: '1 week ago',
    unread: false,
    orderId: 'ORD-2024-0001',
  },
  {
    id: 'n12',
    type: 'payment_refunded',
    title: 'Refund processed',
    desc: 'A refund was sent back to your mobile money.',
    body: 'Your refund for a cancelled item has been submitted to your EVC Plus wallet. Timing depends on your provider.',
    time: '1 week ago',
    unread: false,
    orderId: 'ORD-2024-0004',
  },
  {
    id: 'n13',
    type: 'weekend_offer',
    title: 'Last chance — weekend sale',
    desc: '15% off outdoor lounge ends tonight.',
    body: 'Final hours for the Sunhaven weekend offer. Tap Shop and apply WEEKEND15 before midnight.',
    time: '8 days ago',
    unread: false,
    productImage: 'product-images/sunhaven-outdoor-lounge-set-main.jpeg.jpeg',
    productName: 'Sunhaven Outdoor Lounge Set',
    couponCode: 'WEEKEND15',
  },
  {
    id: 'n14',
    type: 'account_security',
    title: 'Password changed',
    desc: 'Your account password was updated successfully.',
    body: 'If you did not make this change, contact Customer Service immediately from Help Center.',
    time: '9 days ago',
    unread: false,
  },
  {
    id: 'n15',
    type: 'order_confirmed',
    title: 'Order confirmed',
    desc: 'Warehouse confirmed items for #ORD-2024-0002.',
    body: 'All items in your order are reserved. Delivery scheduling will follow shortly.',
    time: '10 days ago',
    unread: false,
    orderId: 'ORD-2024-0002',
  },
  {
    id: 'n16',
    type: 'delivery_qr_ready',
    title: 'Delivery QR ready',
    desc: 'Show your QR or PIN to confirm delivery.',
    body: 'Your driver is nearby. Open the order tracking screen to show the delivery QR or 6-digit code.',
    time: '11 days ago',
    unread: false,
    orderId: 'ORD-2024-0002',
  },
  {
    id: 'n17',
    type: 'wishlist_drop',
    title: 'Price drop on wishlist',
    desc: 'Ivory Cloud Sofa Set is now on sale.',
    body: 'An item you saved dropped in price. Open Wishlist to review and add to cart.',
    time: '12 days ago',
    unread: false,
    productImage: 'product-images/ivory-cloud-sofa-set-main.jpeg.jpeg',
    productName: 'Ivory Cloud Sofa Set',
  },
  {
    id: 'n18',
    type: 'support_ticket',
    title: 'Ticket opened',
    desc: 'We received your Customer Service message.',
    body: 'Thanks for contacting MMF. A support agent will reply in this chat as soon as possible.',
    time: '2 weeks ago',
    unread: false,
  },
  {
    id: 'n19',
    type: 'payment_pending',
    title: 'Payment pending',
    desc: 'Waiting for EVC Plus confirmation on #ORD-2024-0005.',
    body: 'Approve the Waafi prompt on your phone to complete payment. The order stays on hold until confirmed.',
    time: '2 weeks ago',
    unread: false,
    orderId: 'ORD-2024-0005',
  },
  {
    id: 'n20',
    type: 'delivery_delayed',
    title: 'Delivery delayed',
    desc: 'Traffic delay for order #ORD-2024-0002.',
    body: 'Your driver is running about 40 minutes late. We will update you when they are nearby.',
    time: '2 weeks ago',
    unread: false,
    orderId: 'ORD-2024-0002',
  },
  {
    id: 'n21',
    type: 'order_cancelled',
    title: 'Order cancelled',
    desc: 'Order #ORD-2024-0006 was cancelled.',
    body: 'This order was cancelled before packing. If a payment was captured, a refund is being processed.',
    time: '3 weeks ago',
    unread: false,
    orderId: 'ORD-2024-0006',
  },
  {
    id: 'n22',
    type: 'coupon_expiring',
    title: 'Coupon expires tonight',
    desc: 'HOME10 expires at midnight.',
    body: 'Use HOME10 before it expires to save 10% on living room sets at checkout.',
    time: '3 weeks ago',
    unread: false,
    couponCode: 'HOME10',
  },
  {
    id: 'n23',
    type: 'wishlist_stock',
    title: 'Low stock alert',
    desc: 'Walnut Dining Bench — only 2 left.',
    body: 'A wishlist item is almost sold out. Add to cart soon if you still want it.',
    time: '3 weeks ago',
    unread: false,
    productImage: 'product-images/walnut-sage-dining-set-main.jpeg.jpeg',
    productName: 'Walnut Sage Dining Set',
  },
  {
    id: 'n24',
    type: 'review_thanks',
    title: 'Thanks for your review',
    desc: 'Your rating for Ivory Luxe was published.',
    body: 'We appreciate your feedback. It helps other customers choose with confidence.',
    time: '3 weeks ago',
    unread: false,
    orderId: 'ORD-2024-0001',
  },
  {
    id: 'n25',
    type: 'delivery_pickup',
    title: 'Warehouse pickup ready',
    desc: 'Items for #ORD-2024-0003 are ready for the driver.',
    body: 'Packing is complete. Your order will move to Out for delivery once the driver collects it.',
    time: '4 weeks ago',
    unread: false,
    orderId: 'ORD-2024-0003',
  },
  {
    id: 'n26',
    type: 'payment_success',
    title: 'Partial payment received',
    desc: 'We received $210.00 toward #ORD-2024-0007.',
    body: 'Your first payment installment was confirmed. Complete the remaining balance to schedule delivery.',
    time: '4 weeks ago',
    unread: false,
    orderId: 'ORD-2024-0007',
  },
  {
    id: 'n27',
    type: 'promo_new',
    title: 'New arrivals in bedroom',
    desc: 'Soft linen bed frames just landed.',
    body: 'Explore the new bedroom collection in Shop — curated for Mogadishu homes.',
    time: '1 month ago',
    unread: false,
    productImage: 'product-images/blush-velvet-arch-bed-main.jpeg.jpeg',
    productName: 'Blush Velvet Arch Bed',
    couponCode: 'BEDROOM5',
  },
  {
    id: 'n28',
    type: 'account_security',
    title: 'New login detected',
    desc: 'Someone signed in from a new device.',
    body: 'If this was you, you can ignore this message. If not, change your password from Settings.',
    time: '1 month ago',
    unread: false,
  },
  {
    id: 'n29',
    type: 'order_placed',
    title: 'Gift order placed',
    desc: 'Order #ORD-2024-0008 was placed as a gift.',
    body: 'We will keep packaging discreet. Track status from My Orders anytime.',
    time: '1 month ago',
    unread: false,
    orderId: 'ORD-2024-0008',
  },
  {
    id: 'n30',
    type: 'support_replied',
    title: 'Warranty question answered',
    desc: 'Support replied about wood finish warranty.',
    body: 'Open Customer Service chat to read the full reply about care and warranty coverage.',
    time: '1 month ago',
    unread: false,
  },
  {
    id: 'n31',
    type: 'order_shipped',
    title: 'Driver is nearby',
    desc: 'Mohamed Ali is 10 minutes away.',
    body: 'Please keep the delivery entrance clear. Have your QR or PIN ready to confirm receipt.',
    time: '1 month ago',
    unread: false,
    orderId: 'ORD-2024-0002',
  },
  {
    id: 'n32',
    type: 'payment_refunded',
    title: 'Refund completed',
    desc: '$89.00 returned to EVC Plus.',
    body: 'Your refund for a returned accessory has landed. Check your mobile money balance.',
    time: '5 weeks ago',
    unread: false,
    orderId: 'ORD-2024-0004',
  },
];

export function getMockUnreadCount() {
  return MOCK_NOTIFICATIONS.filter((n) => n.unread).length;
}
